name: ramp-battery-prediction
channels:
  - defaults
  - conda-forge
dependencies:
  - joblib
  - matplotlib
  - numpy
  - pandas
  - scikit-learn>=0.22
  - seaborn
  - requests
  - pathlib
  - scipy
  - zipfile36
  - pip
  - pip:
      - ramp-workflow
